version: '3'
services:
    app1:
        image: ianwijaya/hackazon
        hostname: app1
        ports:
        - "8081:80"
    approtect:
        image: app-protect:latest
        volumes:
            - ./custom_log_format.json:/etc/nginx/custom_log_format.json
            - ./labpolicy.json:/etc/nginx/labpolicy.json
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "8080:8080"
    elasticsearch:
        image: sebp/elk:793
        restart: always
        volumes:
            - ./logstash/conf.d:/etc/logstash/conf.d
            - elk:/var/lib/elasticsearch
        ports:
            - 9200:9200
            - 5601:5601
            - 5144:5144
volumes:
    elk:            

